ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REPORT_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REPORT_EMAIL_FAILED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'OPERATIONAL_ISSUE_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CARRY_OVER_AVAILABLE';
